// next
import Head from 'next/head'

import '../styles/globals.css'
import type { AppProps } from 'next/app'
import ReduxProviders from '@/components/providers/ReduxProviders'
import Messenger from '@/components/common/Messenger/Messenger'
import { useEffect, useState } from 'react'
import Loading from '@/components/common/Loading/Loading'
import { motion } from 'framer-motion'

export default function App({ Component, pageProps }: AppProps) {

  const [loading, setLoading] = useState<boolean>(true);

  return (
    <>
      <Head>
        <title>AltoTech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {loading ?      
      <Loading setLoading={setLoading} /> : 
      <ReduxProviders>
        <Component {...pageProps} />
        <Messenger />
      </ReduxProviders>}
    </>
  )
}
